name: inspec-bhagya
title: Amazon Web Services  Resource Pack
maintainer: spaterson@chef.io,russell.seymour@turtlesystems.co.uk
summary: This resource pack provides compliance resources for AWS.
copyright: spaterson@chef.io,russell.seymour@turtlesystems.co.uk
copyright_email: spaterson@chef.io,russell.seymour@turtlesystems.co.uk
version: 1.26.1
license: Apache-2.0
inspec_version: '>= 4.18.108'
depends:
 - name: inspec-aws
   url: https://github.com/inspec/inspec-aws/archive/master.tar.gz
supports:
- platform: aws
